# CICD for staging pipeline
name: staging pipeline

run-name: ${{ github.actor }} staging

on:
  push:
    branches:
      - 'main'

  # Allow manual trigger from github actions to test this pipeline
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Install dependencies packages and cli
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node  
        uses: actions/setup-node@v4 
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          # temporary fix https://github.com/oven-sh/setup-bun/issues/82
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{runner.os == 'macOS' && 'darwin' || runner.os}}-${{ runner.arch == 'X64' && 'x64' || 'arm64' }}.zip"
      - name: Install Dependencies
        run: bun install
      # Checks
      - name: Sanity Check
        run: | 
          echo running sanity test...
          ls -l
      # Test
      - name: Linter Test
        run: bun run test:linter
      - name: Unit Test
        run: bun run test:unit
      # Build Binary
      - name: Build Index
        run: bun run build
      # Deployment
      - name: Deploy to Preview App Distributor
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POMODORO_EPOCH }}'
          expires: 3d
          channelId: preview
          projectId: pomodoro-epoch